### ISSUE TITLE
Do we establish what are exceptions that are grounds for council member replacement?

### ISSUE THREAD

**Issue by YaserJazouane** [pyth-network/governance#347]

**Comment by jayantk** [comment]
IMO it would be better to define a process for replacement that could occur at any time rather than explicit grounds, because we don't really have a mechanism for enforcing those grounds. At the end of the day, there are just people voting with their tokens or multisig keys. So we could say e.g., "a council member may be removed by 2/3 vote of token holders", but we can't say "a council member may be removed for negligence"

**Comment by yosky520** [comment]
There will be new problems with token voting - will the voting rights and votes of holding 1 token be the same as those of holding 1 million tokens?! If the voting weights are the same, will the number of votes be the same? How to avoid the large number of votes occupied by large funds to manipulate the votes?!

**Comment by Gordonsstllalive** [comment]
I agree with Jayantk

**Comment by Rorrirray** [comment]
Jayantk makes a valuable point. Swift and decentralised recourse is essential especially in such a trust based environ

**Comment by Fuse-crypt84** [comment]
I agree with Jayantk
